name: Docker Test

on:
  push:
  pull_request:

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run Docker container
        run: docker run --rm my-app
